### PR TITLE
Revised Schema and Seeder

### PR DESCRIPTION
**Pull request by Try-Try-Again**
Updated Schema and population script to store reservations inside a restaurant document.

### CODE REVIEW

**Comment by tiffanyjalovec** [comment]
Did you change 365 to 60?

**Comment by Try-Try-Again** [comment]
> Did you change 365 to 60?

I did. Got tired of watching my screen being a kaleidoscope :P

**Comment by tiffanyjalovec** [comment]
> > Did you change 365 to 60?
> 
> I did. Got tired of watching my screen being a kaleidoscope :P

I think that was a smart move

**Comment by jbalbin3** [comment]
I like how you organized and named your functions.  Looks good.

**Pull request merged**
